### ISSUE TITLE
ac86u改版梅林384.14无法正常启动

### ISSUE THREAD

**Issue by OutisJ** [KOP-XIAO/Clash-Merlin#13]
在运行./clash -d .命令时，出现
FATA[0000] Parse config error: yaml: invalid leading UTF-8 octet
换了多套策略也没有用，求大神解答

**Comment by 1298882690** [comment]
这个不是说你的配置文件格式有问题吗,这和系统没关系,可能是你在电脑上编辑的时候改了编码格式,用notepad ++这种东西改回去试试
